spring:
  application:
    name: six-degress-service
  docker:
    compose:
      lifecycle-management: start_only
  threads:
    virtual:
      enabled: true
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j

management:
  endpoints:
    web:
      exposure:
        include: '*'

tmdb:
  api:
    url: "https://api.themoviedb.org/3/"
    token: ${API_TOKEN}

logging:
  level:
    org.kidoni: debug
