spring:
  application:
    name: six-degress-service
  docker:
    compose:
      enabled: false


  threads:
    virtual:
      enabled: true


tmdb:
  api:
    url: "https://api.themoviedb.org/3/"
    token: ${API_TOKEN}

logging:
  level:
    org.kidoni: debug
